### ISSUE TITLE
Grammar incorrect for simple variable declarations

### ISSUE THREAD

**Issue by rgallion** [taggandrew/atom-language-dxl#1]
A series of simple variable declarations such as the following are incorrectly parsed by this package.

bool b
int i
real r
string s

In this case, 'bool' and 'real' are correctly marked as 'storage.type.fundimental.dxl', but 'int' and 'string' are incorrectly marked as 'declaration.variable.dxl'.

**Comment by taggandrew** [comment]
Thanks Roger, will get that sorted out. Comments much appreciated, helps me learn faster on what is a new platform for me.

Rgds
Andrew
