### ISSUE TITLE
CHANGELOG.md incorrect

### ISSUE THREAD

**Issue by rgallion** [taggandrew/atom-language-dxl#5]
the 0.3.0 version of CHANGELOG.md contains only the following:

0.1.1 - Second Release
- Added 'for object in module do' snippet

**Comment by taggandrew** [comment]
No worries, will fix. I had a bit of trouble with the release process, need to draw myself a flowchart for next time.

Rgds
Andrew

**Comment by rgallion** [comment]
Thanks.
